### ISSUE TITLE
Temperature no longer taken into account (regression on #57 ?)

### ISSUE THREAD

**Issue by gillett-hernandez** [raiguard/RateCalculator#107]
### Description

The temperature of input and specifically output fluids is no longer displayed or taken into account, so if a recipe simply warms or cools a fluid it will show up as fully balanced input and output in rate calculator, rather than being separate line entries for each temperature or temperature range.

see issue #57 as it is basically identical to this one.

### Reproduction

precondition: installed py mods
place regenerative heat exchanger with a brick warming recipe
use rate calculator

**Comment by raiguard** [comment]
Gah, I completely forgot about this, my apologies. What I would give for automated testing...

**Comment by gillett-hernandez** [comment]
ty for the quick turnaround/response!
