### ISSUE TITLE
Air pollution count is missing

### ISSUE THREAD

**Issue by dxfh00** [raiguard/RateCalculator#109]
### Description

Hello. In version 3.x there is no possibility to count the air pollution in the chunk. Is there a possibility to return it in the new version? (sorry for the text, I used google translator)

**Comment by raiguard** [comment]
Pollution rates were removed because they added a lot of complexity to the calculations for not much benefit. I don't wish to add them back unless many people request it.

**Comment by dxfh00** [comment]
Your pollution indicators are the most convenient for those who play with mods. I can give an example: SE+K2, where you can control the evolution of Biters. Counting the pollution of chunks allows you to oppose the filters of pollution cleaning, which allows you to supplement Factorio with new possibilities

**Comment by raiguard** [comment]
I'll look into it, but no promises one way or the other.

**Comment by TheoMarque** [comment]
This is VERY useful information for me creating playtrough (300h of game play) to reduce pollution to minimum, version 3.0 makes your mod useless for me. The same for electricity balancing accumulators and power peaks. The same is for heat production for mods like Turbines ++. New version is a big regression making your mod less useful than MaxRateCalculator from other creator.

**Comment by raiguard** [comment]
Heat and electricity are still calculated though.

**Comment by raiguard** [comment]
Power consumption is disabled by default but can be re-enabled in the settings. However, as you note, it will only occupy one line and is no longer an entirely separate category. This was done to greatly simplify the mod, whose primary purpose is the materials rates.
