### ISSUE TITLE
Add an option to display production/consumption rates in the new table

### ISSUE THREAD

**Issue by endrjux** [raiguard/RateCalculator#111]
I fully understand why GUI was redesigned and also that old GUI is not coming back. I propose an enhancement that would be a compromise which could help people used to the old GUI find what they need: IMO the only thing that is missing are production/consumption rates in the table. Since the idea was to hide detailed information by default, displaying those could be optional, turned off by default.

**Comment by Tsunayoshi** [comment]
+1

**Comment by Tsunayoshi** [comment]
Hi again, in answer to #108 - you exactly put things in words i could not locate. I actually know about the shift + left click option and I read about the shift + right click option (it a great one! I love it).
The thing is before u could see in the table ok i need 5 more buildings (in same configuration) of x to balance it. Now i have to randomly test around with adding and removing buildings. It's not bad and might also be much closer to the game (tbh) but yeah it's not as easy to find this out as before. Reading the tooltip btw solves that a bit while still it's not one look, it's reading to the point where ur information is. 

So to keep the new ui and function my suggestion would be to get slightly back into table view on the production side and in the tooltip (if that's possible). And maybe (i know this one still ask for old stuff) have a checkbox like u did for energy consumption, to see the per machine in/out on the ui. Basically a checkbox to move the tooltip numbers to the ui.

No idea if that's also an option for all other requests in that direction but i would be happy with this.

**Comment by raiguard** [comment]
> The thing is before u could see in the table ok i need 5 more buildings (in same configuration) of x to balance it.

I'm confused, the new UI shows the same "net machines" metric as the old UI did. That tells you how many more machines you need. Am I missing something here?

For example, both UIs tell me that I need two more machines (or, at least. 1.33 more machines) making low density structures to balance the ratios:

![image](https://user-images.githubusercontent.com/3515394/236643363-f701e91f-f8cd-4c98-a1e0-3b26fc0e42a9.png)

![image](https://user-images.githubusercontent.com/3515394/236643440-38291978-4aae-41d6-b5cf-5ab87689408e.png)

**Comment by raiguard** [comment]
As for aligning numbers in the tooltips, I wanted to do that, but unfortunately it is straight-up impossible with the current API.

**Comment by endrjux** [comment]
I didn't have any problems with the machines count, for me it's actually more readable than before. My main objection is prod/cons rates that are hidden: this is partially because intermediates are not always only intermediates. It somewhat depends on what is being calculated, sometimes I want to make sure all numbers are correct, and net rate alone might not be enough. It's simply easier to read the table instead of mousing over to see the tooltips. I get that this might be viewed as "advanced" usage, so it's ok to hide it by default.

The other issue, which I don't think can be solved, is what I mentioned above: intermediates are sometimes also outputs. The mod unfortunately can't know what is the intention of the calculation or the build itself, so I'm not sure how to improve this. Overall I think the distinction between inputs and outputs is good (so again, this is an improvement over the previous version).

**Comment by raiguard** [comment]
Yeah, the way rate calc has always been "meant" to be used is for a single "subfactory" at a time. The new interface splits your subfactory's inputs, outputs, and intermediates based on what it sees. Doing anything fancier would require a full-blown solver and is beyond the scope of this mod.

I agree that adding a way to see input/output rates is a good idea, so I'm doing some experiments.

**Comment by Tsunayoshi** [comment]
Omg 😳 i see my mistake here. I thought the number in the middle shows the net rate of the item but it actually show the number of machines that's missing or too much! Ok that explains why i am so unhappy with it, coz i read it wrong. Theeeen~ i have only 1 feedback. Maybe add headers or measures to the shown numbers. Like -1.33 machines and +0.5/s, this would clarify. I literally thought i have to check the tooltip then and calculate myself how much machines i need to get 1.33/s more. That's for that 2 pics! This made me realize that there is nothing missing for me! I am sorry for being stupid ;)

**Comment by raiguard** [comment]
No it's alright, don't feel bad! This has made it _very_ clear that it needs better documentation. I am going to make a graphic with numbers that explains what each thing means and add that to the readme, the mod portal page, and create a tips&tricks item as well.

**Comment by Clam-** [comment]
Hi,

@raiguard by
> input/output rates separately on intermediates

Do you mean being able to see the net rate of the downstream consumer?
For example in this:
![Screenshot 2023-05-15 183844](https://github.com/raiguard/RateCalculator/assets/985835/499eb9a4-a467-4c7c-828e-68e9ff432274)

Sure, it shows me how many chemical plants I have in excess, but I would like to know how many more furnaces I need to "consume all of the produced output" of the chemical plants.
I believe the old table layout showed that, it would show like +2.something in the furnace row I think(?)

If that's what you mean then I'm looking forward to the experiments!

Thanks heaps.

**Comment by Zyst** [comment]
Has anyone made a fork pinned to v2 on the mod portal?

**Comment by schmorp** [comment]
@Zyst done, as RateCalculatorClassic

**Comment by raiguard** [comment]
> I believe the old table layout showed that, it would show like +2.something in the furnace row I think(?)

@Clam- The old UI didn't actually show this, but it sounds like a good thing to show so I'll see if I can add it.

**Comment by raiguard** [comment]
![image](https://github.com/raiguard/RateCalculator/assets/3515394/97814524-dbda-4bdd-af45-72153cfc4270)
Here is what I came up with for this. I think it ended up pretty ok!
