### ISSUE TITLE
Usage in Map Editor

### ISSUE THREAD

**Issue by AkaraVortex** [raiguard/RateCalculator#114]
### Description

Calculating anything in Map Editor (and in any custom user scenario) results in fatal GUI bug.

![image](https://user-images.githubusercontent.com/132821993/236675482-756673de-1813-49d1-9842-d635df062e9e.png)

[factorio-current.log](https://github.com/raiguard/RateCalculator/files/11414873/factorio-current.log)

**Comment by raiguard** [comment]
This happens because the mod wasn't initialized properly. The `on_init` event simply isn't being raised, so all sorts of things will be broken. There isn't really a good solution for this, I recommend starting a regular game and using `/editor` instead.
