### ISSUE TITLE
Rate precision

### ISSUE THREAD

**Issue by AkaraVortex** [raiguard/RateCalculator#115]
Add ability to choose floating point precision, not only it got a lot more rough in update, but it removed ability to see unrestricted in length value when hovering cursor over it.
Even if there only so few examples examples where you need 5 decimal places (old default was 4), but now it is excruciatingly unprecise.

In this example the difference is 5%, and there is not option to see exact value.

![image](https://user-images.githubusercontent.com/132821993/236677733-d13a3947-7289-4ad2-ae55-6113ee331d73.png)

![image](https://user-images.githubusercontent.com/132821993/236677724-2feeb00c-5525-46e0-93af-9c0ebe4c5c83.png)

**Comment by gxmat** [comment]
I second this. I get that the UI update was to make it simpler but the precision should be left at 3 decimal places imo. It made the mod really useful in comparing similar designs but now I can't make a judgement. 

Anyone who even thinks of using this mod is generally doing it for optimization purposes but this is hard to do with one decimal place.

**Comment by credomane** [comment]
I'll 3rd this. While I do like the new look I dislike the loss of precision and info hidden behind mouse-hover. Especially the "net machine" column. Really *really* ***really*** missing that.

**Comment by raiguard** [comment]
@credomane The net machines are still shown in the new UI - it's the number in parenthesis next to the intermediate machine counts.
![image](https://github.com/raiguard/RateCalculator/assets/3515394/74f8e694-8af3-4d51-8901-fcf0ac979155)

**Comment by credomane** [comment]
So this is where I left that comment. Yeah I finally figured that out a week later then I couldn't find my original comment to amend that.
