### ISSUE TITLE
Liquid input defaults to oil when you chose transport belt sort option

### ISSUE THREAD

**Issue by GudilinAC** [raiguard/RateCalculator#116]
### Description

Working on refined concrete bp. It has water input (shown in "per second" screen): ![image](https://user-images.githubusercontent.com/22715533/236873063-ffb45721-9830-4080-bb27-366a3d0e0e70.png)
When you switch to "Transport belt" screen, liquid input is still there (with dash, cause u can't calculate it, obviously), but it icon defaults to oil icon, should be water icon instead:
![image](https://user-images.githubusercontent.com/22715533/236873123-027851ac-2d87-4c65-8ab0-36eceba9f077.png)
Note: I don't think liquid showing on that screen with a dash is an error, cause it reminds me that there is actually some other input. Sometimes I forget this when was using previous version, when was placing train stops.

### Reproduction

1. Place assembler with concrete recipe (any recipe consuming water)
2. Use rate calculator
3. Switch to "transport belt" view

**Comment by raiguard** [comment]
That's actually not oil, it's water shown in greyscale. It's working as expected. If you select a storage tank or fluid wagon to measure against, all of the items will be greyed out.
