### ISSUE TITLE
No longer calculates power requirements for machines?

### ISSUE THREAD

**Issue by Mutant15** [raiguard/RateCalculator#118]
### Description

I'm just curious where the ability to show power requirements of machines went? I notice it will calculate what generators produce but not what machines use? Am I severely missing something or is this just gone now? If so I hope it makes a comeback...

**Comment by raiguard** [comment]
It's disabled by default, but can be re-enabled in the mod settings.

**Comment by Mutant15** [comment]
I must've missed it. Thank you for the quick response I appreciate it.
