### ISSUE TITLE
non recoverable error

### ISSUE THREAD

**Issue by bambuuka** [raiguard/RateCalculator#122]
### Description

Rate Calculator  2.4.8 caused a non recoverable error.

![image](https://github.com/raiguard/RateCalculator/assets/136406793/7a4345e4-a701-4cc7-87c3-8af8a6fa566b)

I wanted to use version 2 since I need electric usage calculator, plus the table make it very much easier to read rather than what the current version is using.

### Reproduction

1. change version in mod page.
2. load latest save.

**Comment by raiguard** [comment]
Downgrading the mod version is never going to work well. If you want to use the old interface, you can use the [Rate Calculator Classic](https://mods.factorio.com/mod/RateCalculatorClassic) mod.
