### ISSUE TITLE
selection crash

### ISSUE THREAD

**Issue by Alkumist** [raiguard/RateCalculator#123]
### Description

The mod Rate Calculator (3.2.0) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event RateCalculator::on_player_selected_area (ID 51)
LuaGuiElement API call when LuaGuiElement was invalid.
stack traceback:
	[C]: in function '__newindex'
	__RateCalculator__/scripts/gui.lua:51: in function 'update_gui'
	__RateCalculator__/scripts/gui.lua:523: in function 'show'
	__RateCalculator__/scripts/gui.lua:518: in function 'build_and_show'
	__RateCalculator__/scripts/calc.lua:143: in function 'handler'
	__core__/lualib/event_handler.lua:47: in function <__core__/lualib/event_handler.lua:45>
![image](https://github.com/raiguard/RateCalculator/assets/23058281/f9578cef-c655-475a-8b67-2015b50f9ec2)

### Reproduction

using 3.2.0 drag select

**Comment by carter-thaxton** [comment]
I'm seeing the same thing.  I can't select anything in the latest version (3.2.0) without encountering this crash.

**Comment by carter-thaxton** [comment]
Reverting back to 3.1.2 still works.

**Comment by Alkumist** [comment]
hmm. works fine all by its self... i wonder where the issue occurs

**Comment by Alkumist** [comment]
> hmm. works fine all by its self... i wonder where the issue occurs

works fine with all the same mods as when it crashes in my save, when in the test world

**Comment by Alkumist** [comment]
it appears to be a migration issue.

steps I took to fix:
1 disable rate calculator
2 load save
3 save
4 enable rate calculator 3.2.0
5 load save
6 profit

**Comment by raiguard** [comment]
Can someone please upload their save file? I tested migration from 3.1 and I can't reproduce this.
