### ISSUE TITLE
Feature Request: Highlight bottleneck step and calculate max end product given that bottleneck.

### ISSUE THREAD

**Issue by CricketBr** [raiguard/RateCalculator#130]
In most processes, one step is a bottleneck. Highlighting that step, and calculating the maximum production of the entire chain would save a lot of flipping between this screen and YAFC or Helmod, checking that each intermediate is made in sufficient quantities. I'm not sure exactly how to do it, other than the steps that already have enough input to run at max speed can be ruled out.

**Comment by raiguard** [comment]
Duplicate of #121, #95, and #17.
