### ISSUE TITLE
Any chance you can create a toggle to display inputs/outputs instead of production/consumption?

### ISSUE THREAD

**Issue by apaksl** [raiguard/RateCalculator#132]
Or perhaps I'm just a noob, I only switched to RateCalculator from MaxRateCalculator recently and I'm still getting used to it.

My issue is that I already use FactoryPlanner to tell me how many of each building to use, but in recipes where a consumed item is also produced I would like to be able to see the gross output of the building so that I can plan accordingly for number of output belts/inserters. RateCalculator seems to assume that in my scenario these items would be put directly back into the input, but I haven't found a more elegant way of doing so other than to output onto a belt and send it back to the input belt with a priority splitter.

**Comment by Soul-Burn** [comment]
Options -> Mod settings -> Per player -> Show intermediate output/input rates column.
