### ISSUE TITLE
Ability to select inserter from the world does not appear

### ISSUE THREAD

**Issue by Soul-Burn** [raiguard/RateCalculator#133]
### Description

In previous versions, it was possible to select an inserter from the world, very useful when using Bob's Inserters.

This feature doesn't seem to exist anymore, and replaced with a standard inserter type selector.

### Reproduction

1. Open RateCalculator.
2. Select "by inserters"
3. Click the inserter button

**Comment by raiguard** [comment]
This is correct, you can't select inserters in-world any more. Inserter rates having to do with belts were inaccurate anyway.
