### ISSUE TITLE
IR3: Arc furnaces are not considered

### ISSUE THREAD

**Issue by Sipke82** [raiguard/RateCalculator#138]
### Description

![image](https://github.com/raiguard/RateCalculator/assets/30873812/98622f18-c7b8-429c-8f4c-448f73e17a5c)

**Comment by raiguard** [comment]
If you're talking about the fluids being missing, it's because you have Transport Belts selected as your measure. Fluids can't go on transport belts so it doesn't show them.

**Comment by Sipke82** [comment]
Ahh You are right, im sorry!

**Comment by raiguard** [comment]
It's no problem, that fact isn't terribly clear. I used to grey them out instead of hiding them but that made for a bunch of spaghetti code so I removed it.
