### ISSUE TITLE
[Feature Request] Toggle selection tool with shortcut bar button

### ISSUE THREAD

**Issue by chindraba-work** [raiguard/RateCalculator#146]
### Description:

Clicking the Rate Calc button in the shortcut bar changes the cursor to the selection cursor with the tool's icon. Clicking it a second time with the result GUI open does nothing while clicking it with result GUI close displays the last result GUI, however long ago that was. Even if the last use was some days prior and the game has been saved and closed since then. In the empty cursor case, where the second click restores the previous results, a third click then does nothing.

Clicking an item in the quickbar places that item in the cursor. Clicking that item again will clear the cursor. The exception is with one of the wires. If one end of the wire is anchored, a click on the quickbar will clear the anchor. If the wire is not anchored a second click will clear the cursor, which is the third click if it's anchored.

The GUI itself acts like any other well-behaved Factorio GUI, responding to the Esc or 'Confirm window' key (E)  and to a click on the close 'X'. The tool itself, however, can only be dismissed by the using the 'Clear cursor' key (Q).

### Desired action:

Clicking the shortcut button with anything other than the Rate calc tool in the cursor, including an empty cursor, switches to the Rate calc tool cursor, as it is now. Clicking the button with the tool in the cursor clears the cursor, as it does for items. If the recall last GUI is a desired feature (why I don't know, but it might be) then clicking the button with no GUI open recalls the last result, as now, and clicking the button with the GUI open dismisses the tool from the cursor. Clearing the cursor can leave the GUI open, if it is, the same as pressing the (Q) does now. 

This would avoid the necessity clearing the tool by mouse requiring that I click an item in the quickbar to switch the cursor and then click the same item to clear that from the cursor. One thing is that it's a second click, in a different spot than the tool's button. The other thing is that it's a 'trick' which might not be known to all users.

Notes:

1. With the wires and remote controls becoming tools, or virtual items, in 2.0, having them operate in the toolbar like they have operated in the quickbar so far would reduce the cognitive load when 2.0 releases.
3. If you can make this work for Rate calc it can be set as an enhancement for the main game in 2.0.1, or somewhere down the road, for the other 'selection' tools - copy, cut, paste, blueprint, deconstruction planner and upgrade planner.
4. Whether or not to highlight the button when selected, such as is done with inventory, or the toggles for roboport and exoskeleton, or to leave it unchanged if active or not, is a design decision which I'm not competent to make, and which I have to opinion on.

**Comment by raiguard** [comment]
Other selection tools, i.e. copy, paste, blueprints, upgrade planners, and deconstruction planners, do not clear if you click the shortcut button again. You might have some other mod that is making that behavior.

Just press Q.
