### ISSUE TITLE
Crash on Ctr/F

### ISSUE THREAD

**Issue by Cyclomactic** [raiguard/RateCalculator#148]
### Description

Issue when using Ctr/F. IDK if this is related to #123 & #124. Here is a clip of the event : https://clips.twitch.tv/KitschyInventiveMarrowOneHand-p3c5p0h8_72KcGWJ

> The mod Rate Calculator (3.2.4) caused a non-recoverable error.
> Please report this error to the mod author.
> 
> Error while running event RateCalculator::on_gui_click (ID 1)
> Error when running interface function RecipeBook.open_page: __RecipeBook__/scripts/gui/info/list-box.lua:84: bad argument #1 of 2 to 'lower' (string expected, got nil)
> stack traceback:
> 	[C]: in function 'lower'
> 	__RecipeBook__/scripts/gui/info/list-box.lua:84: in function 'update'
> 	__RecipeBook__/scripts/gui/info/index.lua:328: in function 'update_contents'
> 	__RecipeBook__/scripts/gui/info/index.lua:606: in function 'build'
> 	__RecipeBook__/control.lua:43: in function 'OPEN_PAGE'
> 	__RecipeBook__/scripts/remote-interface.lua:50: in function <__RecipeBook__/scripts/remote-interface.lua:30>
> stack traceback:
> 	[C]: in function 'call'
> 	__RateCalculator__/scripts/gui-rates.lua:147: in function 'handler'
> 	__flib__/gui-lite.lua:169: in function 'handler'
> 	__core__/lualib/event_handler.lua:47: in function <__core__/lualib/event_handler.lua:45>

**Comment by raiguard** [comment]
This is a crash in Recipe Book that has since been fixed.
