### ISSUE TITLE
Entities that burn fluids sometimes show inaccurate 

### ISSUE THREAD

**Issue by mikelat** [raiguard/RateCalculator#149]
### Description

Rate calculator believes the composter buildings in pyanodons are burning more fluid (sweet syrup) then they are actually burning.

First screenshot is what rate calculator says its using:
![eff1](https://github.com/raiguard/RateCalculator/assets/14167635/d077da77-e6d0-4199-902d-01787e836a82)

Second screenshot is what the building internally says is its consumption rate. From experience this number appears to be accurate:
![eff2](https://github.com/raiguard/RateCalculator/assets/14167635/f8fc8ad4-4fbf-455b-ae4e-8bb35fc0fcd5)

Where I think the problem may lie - the composters use "effectivity" which rate calculator may not be taking into account. It fits the math.
![eff3](https://github.com/raiguard/RateCalculator/assets/14167635/90a22227-ac44-4e4b-82b3-c00d97dfaf52)

Save file that has the appropriate entities/mods loaded up for testing with some beacon scenarios as well:
[py_fuel_burning.zip](https://github.com/user-attachments/files/15818085/py_fuel_burning.zip)

**Comment by ramyalexis** [comment]
Hello @raiguard 
Does not look like that this is fixed. Please see screenshot attached.
And i am using latest version of course.
![usage](https://github.com/user-attachments/assets/3de6c09c-82ef-479d-b1a0-06d06b285dd4)
Current usage: 14.81
Effectivity: 200%
Rate calculator: 7.403
Am i missing something?

**Comment by raiguard** [comment]
Can you upload your save file?

**Comment by ramyalexis** [comment]
Sure.
https://easyupload.io/304nkp

**Comment by raiguard** [comment]
Thanks, turns out I didn't test all variants of fluid energy source. Fixed in a new patch.

What I would give for automated tests...
