### ISSUE TITLE
Productivity misscalculation 

### ISSUE THREAD

**Issue by Chaotic-shadow** [raiguard/RateCalculator#150]
### Description

The math for the amount a building can make is wrong when you add Productivity  past max speed it dose not  calculation  the amount the Productivity. The stays the same maxed out a around 22k but am getting 55k out a min on or 100k when using a bob chemical plant with prod 8 

### Reproduction

get a chemical plant to max speed with Productivity max (I am using the sulfur recipe) 
then keep add more speed to it  you can get out more pass the max it said I can get is 9 270 bets space so around 100k  a min
[mega bass.zip](https://github.com/user-attachments/files/16649045/mega.bass.zip)
[factorio-current.log](https://github.com/user-attachments/files/16649
![20240818103007_1](https://github.com/user-attachments/assets/f042f4bc-d199-4899-8c90-64f14e023f13)
046/factorio-current.log)

**Comment by raiguard** [comment]
Thanks for the report. It looks like I incorrectly cap both the actual crafting and the productivity crafts.

**Comment by raiguard** [comment]
I have decided that I'm not going to fix this. This limitation no longer exists in Factorio 2.0 and the logic around productivity in 1.1 gets really strange when you get > 1 craft/tick.

RC will report correct values in Factorio 2.0.
