### ISSUE TITLE
UI does not open after drag-selecting area.

### ISSUE THREAD

**Issue by I-Am-DB-Cooper** [raiguard/RateCalculator#153]
### Description

The tool is available to select entities in the game, but after selection, no UI/box is displayed.

https://github.com/user-attachments/assets/7d847a06-5dc6-4c58-9217-bc219ad4eba3

The selection correctly displays entity count while selecting.

I have tried both a new game, and loading mod on an existing game.

[SA_01.zip](https://github.com/user-attachments/files/17464245/SA_01.zip)

**Comment by raiguard** [comment]
It works fine for me. Press F4 and make sure you don't have `hide-mod-guis` enabled.

**Comment by I-Am-DB-Cooper** [comment]
Check, hide mod guis was enabled. Apologies. (Not sure how it was enabled)
