### ISSUE TITLE
Pollution shown even when unticked in options.

### ISSUE THREAD

**Issue by ReeceBank** [raiguard/RateCalculator#154]
### Description

![1](https://github.com/user-attachments/assets/eb9487a0-983d-4866-a1d9-ab8d1c249fe1)
![2](https://github.com/user-attachments/assets/5568a2d4-0b5d-4c60-80ed-896d03a5750a)

### Reproduction

Factorio 2.0.7

Space age 'mods' (quality, elevated rails etc)

Factorio Library 0.15.0 (Factorio version 2.0)

+Only this mod enabled.

**Comment by Silver-D** [comment]
Fixed it by replacing checks in ``gui-rates.lua``

The paths are: 
``path == "item/rcalc-power-dummy/normal`` and ``path == ""item/rcalc-pollution-dummy/normal``

instead of ``path == "item/rcalc-power-dummy"``
