### ISSUE TITLE
Can't choose inserter type or belt type to for calculations

### ISSUE THREAD

**Issue by mukkie** [raiguard/RateCalculator#155]
### Description

I can't choose the belt type or inserter type when choosing a "timescale".
Factorio 2.0.x

### Reproduction

1. alt-x to activate
2. select area
3. choose "Transport belts" on Timescale
4. click on yellow (default) belt to try and change to blue
5. no options provided

Same problem with inserters

**Comment by hurricup** [comment]
Game hanged at least once when tried to do so

**Comment by raiguard** [comment]
You are probably still holding the rate calculator tool. You need to dismiss the tool before the button will work. Can you confirm if this is the case?

**Comment by hurricup** [comment]
I can't get rid of it, too awesome :)

**Comment by mukkie** [comment]
That is exactly what I was doing. It's working perfectly now. I don't remember having to do that on the 1.1.x version but I wouldn't be surprised if I just did it automatically. 
Apologies for taking your time and thank you for your help.

**Comment by raiguard** [comment]
This has been fixed on the Factorio side.
