### ISSUE TITLE
Can't open map after Factorio update to Version 2

### ISSUE THREAD

**Issue by Codein1** [raiguard/RateCalculator#156]
### Description

```
Error while running event RateCalculator::on_configuration_changed
__RateCalculator__/scripts/gui.lua:293: attempt to index field 'gui' (a nil value)
stack traceback:
	__RateCalculator__/scripts/gui.lua:293: in function 'destroy_gui'
	__RateCalculator__/scripts/gui.lua:541: in function 'on_configuration_changed'
	__core__/lualib/event_handler.lua:87: in function <__core__/lualib/event_handler.lua:84>
```

Are the details provided in the trace sufficient to diagnose the issue, or would you need additional information to further investigate?
I am running version 3.3.1 of this mod.

Please let me know if I can provide any more context or logs to help with troubleshooting.

Thank you!

**Comment by raiguard** [comment]
This is weird. What version were you running before you updated?
