### ISSUE TITLE
Rate Calculator gives inconsistent values when dealing with beacons with ghosted modules

### ISSUE THREAD

**Issue by SamiL52** [raiguard/RateCalculator#157]
### Description

Testing with only the left oil refiner. All modules are tier 1. Not sure if it happens with other buildings.

With just one beacon affecting it rate calculator gives 17.86 petroleum/s:
![20241025045532_1](https://github.com/user-attachments/assets/a30d5aad-bd97-4b9e-8995-3ea681e9e39f)

With four beacons with ghosted modules it gives 13.8 petroleum/s even though the number of beacons with modules affecting it is still one:
![20241025045733_1](https://github.com/user-attachments/assets/f133140a-4116-440a-a142-e5bb08848e89)

### Reproduction

Mods installed: 
Base Mod
Elevated Rails
Quality
Space Age
Blueprint Sandboxes
Factorio Library
Rate Calculator

A way that seems to reproduce every time for me:
- Have an oil refinery set to advanced oil processing with five beacons, each with two speed modules
- Remove four of the beacons, then use rate calculator on the refinery
- Undo the removal of the beacons, and place them back without placing the modules in them. The modules should now be ghosted.
- Use rate calculator again and the value will be different to what was just given

**Comment by SamiL52** [comment]
After looking again it appears to just be the new beacon mechanics? Placing additional empty beacons around a building will "degrade" the transmission of any others already present. If this is the case this probably isn't a bug.

**Comment by raiguard** [comment]
This looks to be working as intended. You can verify if RC is working correctly by comparing the RC value to the value in the entity tooltip.

![image](https://github.com/user-attachments/assets/af51bf9b-30cb-4d1b-8103-be863e4e5ff6)
