### ISSUE TITLE
[Feature Request] Show power requirements when belts and inserts are selected

### ISSUE THREAD

**Issue by ryantheleach** [raiguard/RateCalculator#162]
The current power requirements are measured in MegaWatts which is time independent.

Currently power requirements only show on per second, minute, hour, and are static no matter what selection is picked.

Therefore, there is zero reason to my knowledge that the power rate can't be calculated and shown when Transport Belt or Inserter is selected.

Edit: (also thanks for the fantastic mod raiguard)

**Comment by raiguard** [comment]
Eh. When you select those two it applies a filter for "only show items". I don't think it's worth fixing.
