### ISSUE TITLE
Issues with MOD after version Factorio 2.0.13 release yesterday

### ISSUE THREAD

**Issue by Eclipse4Ever** [raiguard/RateCalculator#166]
### Description

Hi, I got an 403 error after the latest Factorio release yesterday when using your MOD.

2024/11/01 10:42:10 | stdout | Download failed: Code 403.
2024/11/01 10:42:10 | stdout | Downloading RateCalculator_3.3.2.zip
2024/11/01 10:42:10 | stdout | Checking for update of mod RateCalculator for factorio 2.0.13 ...

**Comment by Eclipse4Ever** [comment]
Manual download of 3.3.2 works on version 2.0.13

**Comment by raiguard** [comment]
Mod portal issues should be reported on the Factorio forums.
