### ISSUE TITLE
Steam Temperature seperating steam that is technically the same.

### ISSUE THREAD

**Issue by xilef310** [raiguard/RateCalculator#167]
### Description

Im doing Vulcanus Acid Neutralisation Power Plant and when selecting both the chem plant and the nuclear turbines that accept 500c steam it list the steam outputted by the plant as seperate thing from the steam the turbines need.

If you need screenshots tell me but I believe it may be enough?

### Reproduction

1. Build Chemplant Acid Neutralisation
2. Build the Advanced Turbines next to it.
3. Select them with Rate Calculator.
4. Oberserve the Steam being seperated.

**Comment by dpslwk** [comment]
Think Im seeing a smiler issue here, one the Chemical plant doing Acid neutralisation to two Chemical plants doing Steam condensation

<img width="603" alt="Screenshot 2024-11-17 at 18 28 21" src="https://github.com/user-attachments/assets/6403d127-e501-4184-9b1c-03230f467bdb">

Blueprint
```
0eNq1lNtugzAMht/F16ECGo7SnmSqqhSyLhokNAnTqop3nwODqisrY9LETUjsz78dxxc4VC1vtJAW8guIQkkD+fMFjDhKVrk9yWoOORSvvBYFq7ymYmjcERCy5B+QB92OAJdWWMEH3/7nvJdtfeAaDcjIaETDPau8o1atLIFAowy6KeniIMoLIn8TEThDHm6zTYRBSqF5MZjQjtyxwxVsmk7s9Ds7nWFvb9gLRKd2hkGXGdkSI1pmJEuMeE2d4p/vIAhn4An5oUkeXjAN7i6BAK5djjkYy1ntYTuWXBrWn4+n+1PLKoyPVlLpGrt0RlO6QtM14f/VlK3RNLUWpY80sUKUnuSt1Rj/L6ICf1J1aKs3T0jDtcWTx6Li37yg4Pr0NT+1HAuoPczdLKWc9PQvn/2LqNDROEMzhBvmzDiACEwWN7tjsVlVCOsezl09CBSqbphmVqFceOo3WjcLQ7/b4TeX1KqZk9xUzI1KlFK7Yk9zl8A7au+9ojjMaJZFlPp0G8Vd9wm9NdP9
```

**Comment by raiguard** [comment]
This is "working as intended" - the two steams are not considered equal because one has a temperature and one does not. However, I agree that it's suboptimal.
