### ISSUE TITLE
The ingredients required to make the stated rate of output products is incorrect in calculations with intermediates.

### ISSUE THREAD

**Issue by skfnsadkjf** [raiguard/RateCalculator#174]
### Description

When crafting intermediates, the total amount of inputs required is based on the maximum amount that the machines making that intermediate can output, instead of the amount of intermediate products required to satisfy the next step in the crafting chain.

In the image below, the amount of sulfur (and therefore water and petroleum too), required is 50 times larger than can be used because only 1/50th of the sulfuric acid is required. The sulfur should say "2-0.1    | +1.9" instead of "2-5   |  -3" in the last two columns (and the water and petroleum values should be 2.6 and 0.6 instead of 130 and 30).

![factorio rate calculator issue](https://github.com/user-attachments/assets/faa8e5f6-8afa-4b49-aa74-75da50bcbfaf)

I acknowledge that there is a case where one of your intermediates is also a product you output, and therefore the calculator may need to account for that, but in such a case, one should be able to tick a box or drag an intermediate from the intermediates section into the products section to indicate that excess production is required. (I've never actually wanted to do this though, so I doubt it's actually necessary).

The actual in game problems I have look like this: I select a big set of machines and have a question like, 'how much copper/how many belts of copper does this need'.
I know the amount of copper per second here is wrong, but it's quite difficult to work out how much it's wrong by.
![factorio rate calculator issue2](https://github.com/user-attachments/assets/cc8d0638-6d56-4771-94c4-6a2aa1060d38)

**Comment by M10241024** [comment]
I second this. If it doesn't get added I will probably make a fork and add it myself.
