### ISSUE TITLE
[Request] Ignore excess production of intermediates

### ISSUE THREAD

**Issue by firelizzard18** [raiguard/RateCalculator#177]
### Description

To produce 1/s green science, I need 1/s yellow inserter and 1/s yellow belt. But there's no way to get RateCalculator to tell me how much ore I need for that because even a tier 1 assembler produces yellow belts at 2/s. There should be an option or something to tell RateCalculator to calculate the ingredients per second I actually need to produce 1/s green science.

**Comment by bernhardkohlhaas** [comment]
I second this request. It would be great to have both the needed amount for raw materials for the current build (as is provided now) **and** the actually needed amount of raw materials, based on the demands of the finished product(s). 

Most times the demand of the finished products will be less (since frequently intermediates are overbuilt, if only a bit), but if intermediates are underbuilt, the actual demand of raw materials for the finished products could be higher.

**Comment by raiguard** [comment]
This is deceptively complex and would require a full-blown matrix solver to calculate.

**Comment by bernhardkohlhaas** [comment]
> This is deceptively complex and would require a full-blown matrix solver to calculate.

I don't understand why it would be so difficult.

You already identify what the finished goods ("Products") are for a selected area. All you need to do is to go down the tree of intermediates to the ingredients, which you also already do. Then calculate the necessary input numbers for those ingredients based on the the number of production entities (assemblers/chemical plants/smelting) units for the finished goods and the beacons applied to them. 

You only would pay attention to the intermediate production units for the sake of determining that you need to drill down to their ingredients, you just ignore their numbers and beacons.

Effectively you would treat all intermediates as if they were produced +/- 0, that is at the exact quantity required by the finished goods (Products).

**Comment by kaedys** [comment]
@bernhardkohlhaas late to this, but I recommend something like [Factory Planner](https://mods.factorio.com/mod/factoryplanner), which does in fact have the aforementioned matrix solver built in.  Much better way of identifying how many of what inputs and what buildings at each step are needed for N final products.

Also, the main reason you need a matrix solver is something like oil cracking.  One building consumes heavy oil to make light oil, one consumes light oil to make petroleum, and the refineries output all 3, and then you need X light oil for this plant making rocket fuel, and Y petroleum for this one making plastic, and Z heavy oil for this one making lubricant.  How much crude oil do you need?  Do you have enough cracking plants to keep everything balanced?  Solving that requires solving a series of equations, not a single equation, and that's exactly what a matrix does, it solves series of equations.

Also, what if you do in fact what some of those intermediates as output?  I'm making refined concrete, which requires concrete as an input, but I _also_ want some concrete out for stuff that requires it.  So discarding the excess output of concrete in that case would not be useful, as concrete is in fact both a final product and an intermediary.
