### ISSUE TITLE
Surface's solar power multiplier not taken into account for solar power output

### ISSUE THREAD

**Issue by CoconutThunder** [raiguard/RateCalculator#178]
### Description

In RateCalculator 3.3.2, a surface's solar power multiplier does not appear to be taken into account for solar power output.  This might be a regression of a bug fixed in RateCalculator 2.4.3.

![solar-efficiency](https://github.com/user-attachments/assets/0c44510b-7b1d-4cea-9697-a552167c5ee8)

### Reproduction

1. Construct a solar panel on a surface orbiting Nauvis.
2. Inspect solar panel using RateCalculator cursor.
3. Observe power product does not match power output reported in base game tooltip.

Let me know if you'd like a save file to test this with.

![version](https://github.com/user-attachments/assets/fe5f04b1-cf40-4c25-adb6-b53472bdc813)

**Comment by raiguard** [comment]
The code should be accounting for this, but the API read is returning `1` on all surfaces. This appears to be a bug in Factorio itself. I will look into it tomorrow.
