### ISSUE TITLE
Is there any way to calculate actual output rate if intermediates are rate-limited?

### ISSUE THREAD

**Issue by thedamnatus** [raiguard/RateCalculator#180]
So basically. Let's assume that item A is made in an assembler every second. So item A is 1/s. 
Recipe for item A is the following: 1 copper wire and 10 processing units. 
Now, let's say I cannot make a factory that will provide 10 processing units each second, but I can provide 2 each second. In this example it's easy to calculate (2 is 20% of 10, so 1 second * 20% = one item A every five seconds), but not in all cases. 
So, using the rate calculator mod, can I see displayed somewhere, how many item A's my factory will make, because it only shows 1/s in any case, even if the assembler is limited by the intermediates rate.

**Comment by raiguard** [comment]
See #121.
