### ISSUE TITLE
RC isn't calculating pY's Nexelit miners properly

### ISSUE THREAD

**Issue by jigsaw3xD** [raiguard/RateCalculator#182]
### Description

From what i understood this is a very unique machine that's disabled by script most of the time and the production speed is based on the amount of different creatures (that are placed in the machine like modules) consuming different types of food. Rn RC outputs a number that clearly isn't being calculated properly.

![yXPq7QBlyj](https://github.com/user-attachments/assets/85535c4f-c883-46b1-8461-d7573dd3a092)
![vOLyzRbgFa](https://github.com/user-attachments/assets/dee32e9d-eb2d-402a-9cc7-ae745fe5c78f) ![jHZi0Rmfuy](https://github.com/user-attachments/assets/3353dc08-5d53-4b77-972d-06e2966efdf9)

People on discord say that this is the only building that RC has issues with but I haven't checked it personally

**Comment by raiguard** [comment]
There isn't really a good solution here - this is a heavily scripted entity, so rate calc cannot know how much it will output.

**Comment by notnotmelon** [comment]
This machine's output speed also depends on the configuration of your ore patch. It's impossible for RC to calculate this value.

**Comment by jigsaw3xD** [comment]
Can it be done with a formula maybe? The only random variable seems to be the distance digosaurs go to (and the time they take) to mine the ore and for that you can take a hardcoded number cos furthest and closest distance will always be the same. Everything other variable is taken from the game - how many and which "modules" are in use, which food is being used, etc.

P.S. I'm only replying cos rai didn't close the issue so I assume this is still up for discussion and potential solution proposal (I think? I don't know how github works, sorry).

**Comment by raiguard** [comment]
I was going to ask melon before closing the issue, but if he agrees that it's impossible then there is nothing more to be done.

**Comment by notnotmelon** [comment]
> Can it be done with a formula maybe? The only random variable seems to be the distance digosaurs go to (and the time they take) to mine the ore and for that you can use a hardcoded number cos furthest and closest distance will always be the same. Every other variable could be taken from the game - how many and which "modules" are in use, which food is being used, etc.
> 
> P.S. I'm only replying cos rai didn't close the issue so I assume this is still up for discussion and potential solution proposal (I think? I don't know how github works, sorry).

This would only be true if 100% of the radius was populated with minable tiles.
