### ISSUE TITLE
productivity cap fix (fix for #181) doesn't account for modified productivity cap

### ISSUE THREAD

**Issue by SandBag777** [raiguard/RateCalculator#184]
### Description

productivity cap was hard coded in the productivity calculation, this doesn't take into consideration that the cap could have been modified

here's the fix i came up with:
at [scripts/calc-util.lua#L249](https://github.com/raiguard/RateCalculator/blob/294e380042d5413db57abf815cb34513170b758c/scripts/calc-util.lua#L249)
change `local productivity = math.min(entity.productivity_bonus + recipe.productivity_bonus + 1, 4)`
to `local productivity = math.min(entity.productivity_bonus + recipe.productivity_bonus + 1, recipe.prototype.maximum_productivity + 1)`

**Comment by raiguard** [comment]
Oops, I didn't know that you could change this.
