### ISSUE TITLE
Improve the utility of net machines with multiple producers/consumers/byproducts of an item

### ISSUE THREAD

**Issue by chrisr-rh** [raiguard/RateCalculator#95]
#### Is your feature request related to a problem? Please describe.

Yes, a problem but not a bug. The "net machines" column is misleading. Whenever there are multiple, different recipes in a chain that produce an item, or whenever a consumer produces part of its ingredients, usually as a byproduct (e.g., A is consumed to become B + 50% A), the net machines utility is diminished at best, unusable at worst. For instance, with the proper balance of machines, you can get the net machines to be 1.000 suggesting one machine could be removed to balance the equation; it cannot. In the byproduct example above, removing one machine would put the chain at a deficit. This problem is exacerbated when using the "multiplier" slider when scaling up large chains. 

Note that the "machines" column suffers from this labeling, but not as egregiously since it can be interpreted as "2 machines producing, 1 machine consuming" even though there are only two machines in the production chain.

#### Describe the solution you'd like

I want net machines to guide me in balancing production chains, instead of resorting to trial and error.

In an ideal world, I would like "net machines" to have an intuitive meaning. A +1.000 means you can remove one full machine; a -1.0000 means you need to add one full machine. I realize, however, that there can be multiple recipes producing and consuming the same item in a production chain. In this case, when it isn't straightforward--that is to say, there are multiple consumers or multiple producers of the same items--the value in net machines is annotated in some way. For example, red/green could have companion colors; or an icon be next to the number. In this case, hovering over the number would have a tooltip showing the ratio of recipes that led to that result (e.g., +0.7001 Recipe_Foo and +0.2999 Recipe_Bar). In this way, when one of the recipes in the tooltip reaches +1.000 or -1.000, the player knows she can remove or add one machine that uses the respective recipe to bring balance to the Force.

This treatment could be applied to "net rate" as well to give the user more information as to what recipes are contributing to the rate.

**Comment by raiguard** [comment]
Sourcehut ticket: https://todo.sr.ht/~raiguard/factorio-mods/6

**Comment by raiguard** [comment]
Unfortunately, this isn't nearly as straightforward as it seems. Doing this would require solving a system of equations, which is the kind of thing that Helmod and Factory Planner do. Doing so would significantly increase the scope and complexity of Rate Calculator.
