### ISSUE TITLE
Option to exclude trees?

### ISSUE THREAD

**Issue by lane-ftw** [raiguard/RateCalculator#98]
I'd like to have a keybind and/or an option in the GUI to select with Rate Calculator while ignoring trees.
Would make large/very large selections faster to compute for those of us that leave trees. 
Maybe a popup/tooltip warning about not computing trees for gatherable wood resources/ pollution?

**Comment by raiguard** [comment]
You can shift+scroll with the selection tool to filter it to select entities for a specific measure. This should solve the issue.

The 3.0 rewrite won't select trees at all, and won't spread the calculations over time any more, which will also fix this issue.
